### ISSUE TITLE
想问下有没有这篇论文的数据预处理脚本~

### ISSUE THREAD

**Issue by cyuyande** [chenxy99/SGAN#1]
想问下有没有这篇论文的数据预处理部分的脚本~好像没有数据预处理的脚本运行不出来。

**Comment by chenxy99** [comment]
Hello,

I uploaded the processed JSON data into [Huggingface Dataset](https://huggingface.co/datasets/chenxy99/SGAN). You can try it.

Best regards,
Xianyu

**Comment by chenxy99** [comment]
I also upload the script https://github.com/chenxy99/SGAN/blob/main/src/preprocess/process_data.py to handle the raw JSON data if you are interested in it.
